package BackEnd;

import java.awt.*;

/**
 * @author Deekyech
 * This is a class which has been created to scale the mouse events
 * generated by the controller with the victims screen size.
 */
class ResolveDimensions {

    /**
     * ******************************************************************
     *                            CONSTRUCTOR
     * ******************************************************************
     */
    /**
     * This constructor is used to initialize the resolveDimensions object
     * in the ScreenSharingEventHandling class. It initializes the scaling
     * factors x and y for future use.
     * @param victim : Dimension of the victim's screen size.
     * @param controller : Dimension of the controller's screen size.
     */
    public ResolveDimensions(Dimension victim, Dimension controller) {
        scalingFactorX = getScalingFactorX(victim, controller);
        scalingFactorY = getScalingFactorY(victim, controller);
    }

    /**
     * This method will scale x coordinate according victim's screen size.
     * @param x : the x coordinate at controller's screen where mouse event
     *            is generated.
     * @return  : translated point x according to victim's screen size.
     */
    public double getScaleX(double x) {
        return scalingFactorX*x;
    }

    /**
     * This method will scale x coordinate according victim's screen size.
     * @param y : the y coordinate at controller's screen where mouse event
     *            is generated.
     * @return : translated point y according to victim's screen size.
     */
    public double getScaleY(double y) {
        return scalingFactorY*y;
    }

    /**
     * This method will calculate the X scaling factor which will be used for scaling
     * X coordinate at every mouse event.
     * @param victim : Dimension of victim's screen size.
     * @param controller : Dimension of controller's screen size.
     * @return : X scaling factor
     */
    private double getScalingFactorX(Dimension victim, Dimension controller) {
        return victim.getHeight()/controller.getHeight();
    }

    /**
     * This method will calculate the Y scaling factor which will be used for scaling
     * Y coordinate at every mouse event.
     * @param victim : Dimension of victim's screen size.
     * @param controller : Dimension of controller's screen size.
     * @return : Y scaling factor
     */
    private double getScalingFactorY(Dimension victim, Dimension controller) {
        return victim.getWidth()/controller.getWidth();
    }
    /*public static void unitTesting() {
        try {
            System.out.println("Enter room width and height: ");
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            double width = Double.parseDouble(br.readLine());
            double height = Double.parseDouble(br.readLine());
            ResolveDimensions rd = new ResolveDimensions(width, height);
            System.out.println("getScaleX at 200: " + rd.getScaleX(200));
            System.out.println("getScaleY at 100: " + rd.getScaleY(100));
        } catch(Exception e) {
            System.out.println(e);
        }
    }
    public static void main(String[] args) {
        unitTesting();
    }*/

    //CONSTANTS
    private double scalingFactorX;
    private double scalingFactorY;
}